
FROM qcdis/miniconda3-pdal:v0.14 AS build
COPY visualize-rasterio-gabriel-pelouze-at-lifewatch-eu-environment.yaml .
RUN conda config --remove channels defaults || true
RUN conda env update -n venv -f visualize-rasterio-gabriel-pelouze-at-lifewatch-eu-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM jupyter/base-notebook AS runtime
COPY --from=build /venv /venv
COPY visualize-rasterio-gabriel-pelouze-at-lifewatch-eu.py .
COPY visualize-rasterio-gabriel-pelouze-at-lifewatch-eu.ipynb .
