name: venv
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.8
  - r-dplyr
  - r-stringr
  - r-dendextend
  - r-stringi
  - r-aws.s3
  - r-fields
  - r-reshape
  - r-vegan
  - papermill
  - ipykernel