name: venv
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.8
  - r-glue
  - r-here
  - r-tidyverse
  - r-rgbif
  - r-knitr
  - r-optparse
  - r-RSQLite
  - r-RSQL
  - papermill
  - ipykernel