
FROM ghcr.io/qcdis/n-a-a-vre/naavre-cell-lter-life-veluwe:v0.1-test.8 AS build
COPY process-bud-burst-data-gabriel-pelouze-at-lifewatch-eu-environment.yaml .
RUN conda config --remove channels defaults || true
RUN conda env update -n venv -f process-bud-burst-data-gabriel-pelouze-at-lifewatch-eu-environment.yaml
RUN conda-pack -n venv -o /tmp/env.tar && \
    mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM python:3.11-slim-bullseye AS runtime
RUN apt update -y && apt upgrade -y && apt install jq -y
COPY --from=build /venv /venv
COPY process-bud-burst-data-gabriel-pelouze-at-lifewatch-eu.py .
