
FROM qcdis/conda-lter-life:v0.1 AS build
COPY consume-climwin-dev-user-name-at-domain-com-environment.yaml .
RUN micromamba update -y -n venv -f consume-climwin-dev-user-name-at-domain-com-environment.yaml
RUN conda-pack -p /opt/conda/envs/venv -o /tmp/env.tar && \
    mkdir /venv && \
    cd /venv && \
    tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM ubuntu:24.04 AS runtime
COPY --from=build /venv /venv
COPY ./ /app/
