name: venv
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.8
  - nbconvert
  - r-jsonlite
  - r-dplyr
  - r-taxize
  - r-purrr
  - r-tidyr
  - r-lubridate
  - r-stringr
  - r-httr
  - papermill
  - ipykernel