
FROM jupyter/r-notebook:70178b8e48d7 AS build
COPY create-file-r-dev-user-name-at-domain-com-environment.yaml .
RUN micromamba update -y -n venv -f create-file-r-dev-user-name-at-domain-com-environment.yaml
RUN conda-pack -p /opt/conda/envs/venv -o /tmp/env.tar && \
    mkdir /venv && \
    cd /venv && \
    tar xf /tmp/env.tar && \
    rm /tmp/env.tar
RUN /venv/bin/conda-unpack

FROM ubuntu:24.04 AS runtime
COPY --from=build /venv /venv
COPY ./ /app/
