name: venv
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.8
  - nbconvert
  - r-lubridate
  - r-raster
  - r-rdwd
  - r-stringr
  - r-purrr
  - r-dplyr
  - r-Rcpp
  - r-terra
  - papermill
  - ipykernel